### ISSUE TITLE
Draft the Homepage and Parameter page for a new SEDAR

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/FSD-SDDD-Automation#46]
Create initial homepage page and new SEDAR page from the [Application Design](https://docs.google.com/document/d/1BVLjYEL7bSJnOnMcQbQ7ZQ7AAnAfSozjqEjdNBDhjhs/edit) layout in the SEDAT Apex working environment. Once the pages have been created and tested in SEDAT, they can then be migrated to the SEFR application.

**Comment by SarinaAtkinson-NOAA** [comment]
@sandraaguilar-noaa can I close this issue?

**Comment by sandraaguilar-noaa** [comment]
I think so :)
