### ISSUE TITLE
Update OBS extraction to DW

### ISSUE THREAD

**Issue by sydneyalhale-NOAA** [SarinaAtkinson-NOAA/FSD-SDDD-Automation#78]
James Primrose's tables will be moved to the Data Warehouse, OBS extraction currently pings his personal schema

- [ ] Change extraction to ping Data Warehouse instead of James' schema and update metadata

**Comment by SarinaAtkinson-NOAA** [comment]
@sandraaguilar-noaa made the change from JPRIMROSE schema to OBSG_OBJ schema. @SarinaAtkinson-NOAA updated the metadata with a new DFD image. The original file of the Visio created diagram is located N:\Users\SAtkinson\SDDD-Automation

**Comment by SarinaAtkinson-NOAA** [comment]
Another task will need to created to update the extraction once OBS data migrated to the Data Warehouse, but this task has not been done yet. TIP and landings will need the same kind of update.
