### ISSUE TITLE
Create Reports 

### ISSUE THREAD

**Issue by sydneyalhale-NOAA** [SarinaAtkinson-NOAA/FSD-SDDD-Automation#81]
Starting with 
- [x] raw Commercial landings 
- [x] TIP raw size data
- [x] TIP confidentiality 

Sandra creating intermediate views to filter extractions to create reports

**Comment by sandraaguilar-noaa** [comment]
Yes, they were implemented.  You can check them on the sedat app.  Let me know if something is missing. Thanks!
