### ISSUE TITLE
Flags for CFLP extraction

### ISSUE THREAD

**Issue by SarinaAtkinson-NOAA** [SarinaAtkinson-NOAA/FSD-SDDD-Automation#82]
Flags developed by Kevin McCarthy located in SAS program N:\FMB\SEDAR\SEDAR82\sas programs\1_coastal logbook data filtering program_flagged_records

Summary of flags that should be created:

1. Gear_flag = Records missing effort information. Name in extraction = FLAG_GEAR
2. Report_flag = Trips that have long delays in reporting. Name in extraction = FLAG_REPORT
3. Report1990_flag = Trips that have long delays in reporting for 1990. Name in extraction = FLAG_REPORT1990
4. Trips missing area information. Name in extraction = FLAG_NOAREA
5. Impute area when missing from area reported for another species on that trip and add flag that area imputed. Impute area in AREA_FISHED field and flag name in extraction = FLAG_IMPAREA
6. Region_flag and region123_flag = Trips fishing in multiple regions. These can be combined in the extraction flag. Name in extraction = FLAG_MULTREG
7. Mult_area_flag and mult_area123_flag = Trips fishing in multiple areas. Also combine in extraction and already field in extraction FLAG_MULTAREA.
8. Multgear_flag = Trips fishing with multiple gears (but assume E and H are identical and S and P are identical). Already field in extraction FLAG_MULTGEAR, but make sure we are using the same combined gears to not count those as different gears in the count.

How do these flags compare to flags created (also by Kevin) for CIDX?

**Comment by sandraaguilar-noaa** [comment]
Hi Sarina,
Thank you for provide me with Kevin code.  

a) Is it possible to add the name of the flag that Kevin on the list you provide me (1..8). 
b) In the sas code, what is the original data source? I may need to track the name of the columns. For example received-unload_date  we don't have a received column on the extraction, probably it is there with a different name.

Thank you!
Sandra

**Comment by SarinaAtkinson-NOAA** [comment]
In that same N drive folder, there is a SAS program "coastal logbook data extraction udp 07312020". This is Kevin's extraction code where he pulls the data from UDP and renames fields. I believe received is the opened_date. You could also see the data that SAS code produced which is in this "N:\FMB\SEDAR\SEDAR82\sas files" folder.  This might help you compare what his flags produce vs. the extraction flags.

I also edited my previous comment to add his variable name and what we would want to call it in the extraction for standardization.

**Comment by SarinaAtkinson-NOAA** [comment]
Flags added and checked
